"""Add Project tenant isolation

Revision ID: 63072458e652
Revises: 450c86fc4015
Create Date: 2026-03-31 17:51:37.446865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63072458e652'
down_revision: Union[str, Sequence[str], None] = '450c86fc4015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('swarm_runs', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'swarm_runs', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'swarm_runs', type_='foreignkey')
    op.drop_column('swarm_runs', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
